apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: mo-task-pvc
spec:
  storageClassName: generic
  accessModes:
  - ReadWriteOnce
  resources:
    requests:
      storage: 500Mi
---
kind: PersistentVolume
apiVersion: v1
metadata:
  name: mo-task-pv
  labels:
    type: local
spec:
  storageClassName: generic
  claimRef:
    namespace: default
    name: mo-task-pvc
  capacity:
    storage: 500Mi
  accessModes:
    - ReadWriteOnce
  hostPath:
    path: "/var/lib/mongo"
---
apiVersion: apps/v1        
kind: Deployment
metadata:
  labels:          
    app: task-db
  name: task-db 
spec:         
  replicas: 1    
  selector: 
    matchLabels:
      app: task-db-pod
  template:
    metadata:
      labels:
        app: task-db-pod
    spec:
      containers:
      - name: mongodb
        volumeMounts:
          - mountPath: /var/lib/mongo
            name: mo-task
        image: mongo:4.2
        ports:
        - containerPort: 27017
      volumes:
      - name: mo-task
        persistentVolumeClaim:
          claimName: mo-task-pvc
      restartPolicy: Always
---
apiVersion: v1
kind: Service
metadata:
  labels:
    app: task-db
  name: task-db-service
spec:
  ports:
    - port: 27017
      targetPort: 27017
  selector:
    app: task-db-pod
  type: ClusterIP