apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: mongo-task-pvc
spec:
  storageClassName: generic
  accessModes:
  - ReadWriteOnce
  resources:
    requests:
      storage: 2Gi
---
kind: PersistentVolume
apiVersion: v1
metadata:
  name: mongo-task-pv
  labels:
    type: local
spec:
  storageClassName: generic
  claimRef:
    namespace: default
    name: mongo-task-pvc
  capacity:
    storage: 2Gi
  accessModes:
    - ReadWriteOnce
  hostPath:
    path: "/var/lib/mongo"
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: task-db
---
apiVersion: apps/v1        
kind: Deployment
metadata:
  labels:          
    app: task-db
  name: task-db 
spec:         
  replicas: 1    
  selector: 
    matchLabels:
      app: task-db
      version: v1
  template:
    metadata:
      labels:
        app: task-db
        version: v1
    spec:
      serviceAccountName: task-db
      containers:
      - name: mongodb
        volumeMounts:
          - mountPath: /var/lib/mongo
            name: mo-task
        image: mongo:4.2
        ports:
        - containerPort: 27017
      volumes:
      - name: mongo-task-volume
        persistentVolumeClaim:
          claimName: mongo-task-pvc
      restartPolicy: Always
---
apiVersion: v1
kind: Service
metadata:
  labels:
    app: task-db
  name: task-db
spec:
  ports:
    - name: mongodb
      port: 27017
      targetPort: 27017
  selector:
    app: task-db
  type: ClusterIP