apiVersion: v1
kind: Service
metadata:
  labels:
    app: task
  name: task
  namespace: default
spec:
  ports:
    - port: 8080
      name: http
  selector:
    app: task
---
apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: task
  name: task
  namespace: default
spec:
  selector:
    matchLabels:
      app: task
      version: v1
  replicas: 1
  template:
    metadata:
      labels:
        app: task
        version: v1
    spec:
      serviceAccountName: task
      containers:
        - image: docker.io/cmwylie19/gloo-portal-demo:latest
          name: task
          env:
            - name: CONNECTION_STRING
              value: mongodb://task-db-service:27017/tasks
            - name: PORT
              value: :8080
          ports:
            - containerPort: 8080
              name: http
      restartPolicy: Always
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: task
